# Generated by Django 2.2 on 2019-05-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользыватель', 'verbose_name_plural': 'Пользыватель'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='departament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workers.Departaments', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользыватель'),
        ),
    ]
