# Generated by Django 2.2 on 2019-05-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='secondname',
        ),
        migrations.AddField(
            model_name='workers',
            name='fullname',
            field=models.CharField(default=1, max_length=255, verbose_name='Фио'),
            preserve_default=False,
        ),
    ]
