# Generated by Django 2.2 on 2019-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20190514_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='ip_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Ip адрес'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='room',
            field=models.CharField(blank=True, max_length=4, verbose_name='Кабинет'),
        ),
    ]
