# Generated by Django 2.2 on 2019-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20190520_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='status',
            field=models.CharField(choices=[('На работе', 'На работе'), ('В отпуске', 'В отпуске'), ('В командировке', 'В командировке'), ('В Больничном', 'В Больничном')], default='На работе', max_length=15, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
