# Generated by Django 2.2 on 2019-05-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_auto_20190522_1145'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workers',
            managers=[
            ],
        ),
    ]
