# Generated by Django 2.2 on 2019-05-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20190522_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departaments',
            options={'ordering': ['id'], 'verbose_name': 'Подразделения', 'verbose_name_plural': 'Подразделения'},
        ),
    ]
