# Generated by Django 2.2 on 2019-05-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_auto_20190522_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workers',
            options={'ordering': ['id'], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='workers',
            name='status',
            field=models.CharField(choices=[('На работе', 'На работе'), ('В отпуске', 'В отпуске'), ('В командировке', 'В командировке'), ('В Больничном', 'В Больничном')], max_length=15, verbose_name='Статус'),
        ),
    ]
